language:
     - node_js
     - python

node_js:
     - "0.10"

python:
     - "2.7"
script:
     - node test.js
     - pytest

before_install:
     - export DISPLAY=:0.0
     - sh -e /etc/init.d/xvfb start

before_script:
     - npm install
