#!/bin/bash

# Downloading tiles for PAX River Naval Air Station

curl "http://c.tile.openstreetmap.org/18/754[05-30]/1009[70-90].png" -o "tiles/18/754#1/1009#2.png" --create-dirs

curl "http://c.tile.openstreetmap.org/17/377[00-24]/504[80-99].png" -o "tiles/17/377#1/504#2.png" --create-dirs

curl "http://c.tile.openstreetmap.org/16/188[52-58]/252[42-49].png" -o "tiles/16/188#1/252#2.png" --create-dirs

