# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_photo',
            field=models.ImageField(default='default.img', upload_to=b''),
        ),
    ]
