# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_img_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_photo',
            field=models.ImageField(blank=True, default='default.img', null=True, upload_to='images/unprocessed_%Y%m%d%H%M%S'),
        ),
    ]
