# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20180614_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='target_id',
        ),
        migrations.AddField(
            model_name='target',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
