# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180614_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='direction',
            field=models.CharField(choices=[('ne', 'North East'), ('n', 'North'), ('nw', 'North West'), ('w', 'West'), ('sw', 'South West'), ('s', 'South'), ('se', 'South East'), ('e', 'East')], default='ne', max_length=20),
        ),
    ]
