# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_target_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='alphanumeric_color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('brown', 'Brown')], default='white', max_length=10),
        ),
        migrations.AlterField(
            model_name='target',
            name='shape_choices',
            field=models.CharField(choices=[('circle', 'Circle'), ('star', 'Star'), ('square', 'Square'), ('triangle', 'Triangle'), ('pentagon', 'Pentagon'), ('quarter_circle', 'Quarter-Circle'), ('semicircle', 'Semi-Circle'), ('trapezoid', 'Trapezoid'), ('heptagon', 'Heptagon'), ('hexagon', 'Hexagon'), ('star', 'Star'), ('cross', 'Cross')], default='circle', max_length=10),
        ),
        migrations.AlterField(
            model_name='target',
            name='shape_color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('brown', 'Brown')], default='white', max_length=10),
        ),
    ]
