# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20180614_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='shape_choices',
            field=models.CharField(choices=[('circle', 'Circle'), ('star', 'Star'), ('square', 'Square'), ('triangle', 'Triangle'), ('pentagon', 'Pentagon'), ('quarter_circle', 'Quarter-Circle'), ('semicircle', 'Semi-Circle'), ('trapezoid', 'Trapezoid'), ('heptagon', 'Heptagon'), ('hexagon', 'Hexagon'), ('star', 'Star'), ('cross', 'Cross')], default='circle', max_length=15),
        ),
    ]
