# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.PositiveIntegerField()),
                ('photo_path', models.CharField(max_length=500)),
                ('photo_longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('photo_latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('photo_altitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
