# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sorter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='alphanumeric',
            field=models.CharField(default='none', max_length=4),
        ),
        migrations.AddField(
            model_name='photo',
            name='alphanumeric_color',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='background_color',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='object_type',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='orientation',
            field=models.CharField(default='none', max_length=4),
        ),
        migrations.AddField(
            model_name='photo',
            name='shape',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_path',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
