# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sorter', '0002_auto_20171118_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='object_type',
            field=models.CharField(choices=[('stnd', 'standard'), ('off-ax', 'off-axis'), ('emer', 'emergent')], default='none', max_length=20),
        ),
    ]
