# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sorter', '0003_auto_20171118_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='orientation',
            field=models.CharField(choices=[('N', 'N'), ('NE', 'NE'), ('E', 'E'), ('SE', 'SE'), ('S', 'S'), ('SW', 'SW'), ('W', 'W'), ('NW', 'NW')], default='none', max_length=4),
        ),
    ]
