# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sorter', '0004_auto_20171118_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='shape',
            field=models.CharField(choices=[('circle', 'circle'), ('semicircle', 'semicircle'), ('quarter circle', 'quarter circle'), ('triangle', 'triangle'), ('square', 'square'), ('rectangle', 'rectangle'), ('trapezoid', 'trapezoid'), ('pentagon', 'pentagon'), ('hexagon', 'hexagon'), ('heptagon', 'heptagon'), ('octagon', 'octagon'), ('star', 'star'), ('cross', 'cross')], default='none', max_length=20),
        ),
    ]
