# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sorter', '0005_auto_20171118_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='alphanumeric_color',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black'), ('gray', 'gray'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('purple', 'purple'), ('brown', 'brown'), ('orange', 'orange')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='background_color',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black'), ('gray', 'gray'), ('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('purple', 'purple'), ('brown', 'brown'), ('orange', 'orange')], default='none', max_length=20),
        ),
    ]
